import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import './styles/all.min.css';
// import './styles/swiper-bundle.min.css';
// import './styles/jquery.magnify.css';
import './styles/custom.css';
import './styles/props.css';
import './styles/responsive.css';
import Headers from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@2.3.0/dist/aos.css" type="text/css"></link>
      </head>
      <body>
        <Headers/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
